### ISSUE TITLE
Add 3-4 questions to check the understanding of README topics

### ISSUE THREAD

**Issue by skibinska** [lucymonie/api-workshop#2]
Hi @lucymonie!

Here are my suggestions for questions:

### 01. Request and response:

1. Could you explain the flow of request-response pattern?
2. What is *responseText* and what do we use to transform it?
3. What is HTTP?

### 02. xmlhttprequest

1. How to create an XHR Request?
2. What and why do we check in *onreadystatechange* function?
3. How many parameters accept *open* method? Could you explain what they are?

### 03. asynchonous

1. What is the difference between synchonous and asynchonous?
2. Could you explain the event loop?

This is just my first thoughts.

**Comment by lucymonie** [comment]
Those are great. I would probably break some of them down into smaller parts, like this:

### Request and response:
1. Ask two people from the cohort to stand up and draw the request-response pattern on the whiteboard and explain what happens
Aside: ask if they know what JSON is to check everyone understands it. If someone from the cohort knows, get them to explain it to everyone.
3. What is the request property `responseText`?
4. What JSON method can we use to transform it into something we can use?
5. What is HTTP?

Then ask them if they have questions and try to answer them.

### XMLHttpRequest
1. How do you create a new XHR object?
2. Why do we check on the `onreadystatechange` property?
3. Bonus question: what is the initial value of `onreadystatechange`? How would you check?
4. How many parameters does the 'open' method expect? Could you explain what they are?

Then ask them if they have questions and try to answer them.

### Asynchronous
1. What is the difference between synchonous and asynchonous?
2. What is the call stack?
3. What is going on in the loupe example?
4. Explain what happens to asychronous tasks that are at the top of the call stack

Then ask them if they have questions and try to answer them.

**Comment by skibinska** [comment]
Nice one. Thanks Lucy! :+1:  :smile:

**Comment by lucymonie** [comment]
And updated questions to reflect the addition of the HTTP readme

### Request and response:
1. Ask two people from the cohort to stand up and draw the request-response pattern on the whiteboard and explain what happens
- Aside: ask if they know what JSON is to check everyone understands it. If someone from the cohort knows, get them to explain it to everyone.
2. What is the request property responseText?
3. What JSON method can we use to transform a responseText string into something we can use?

### HTTP
1. What is HTTP?
2. Name three HTTP methods.
3. What type of status code is 503? How would you find out what it means?
4. Name another communication protocol (bonus points if you name a secure one)

### XMLHttpRequest
1. How do you create a new XHR object?
2. Why do we check on the onreadystatechange property?
3. Bonus question: what is the initial value of onreadystatechange? How would you check?
4. How many parameters does the open method expect? Could you explain what they are?

### Asynchronous
1. What is the difference between synchronous and asynchronous?
2. What is the call stack?
3. What is going on in the loupe example?
4. Explain what happens to asychronous tasks that are at the top of the call stack

**Comment by lucymonie** [comment]
@skibinska do you think we need to include a description of what JSON is? If so, where do you think it should go?

**Comment by skibinska** [comment]
I think one sentence about JSON in first readme is enough. :)

I wrote [here](https://github.com/lucymonie/api-workshop/issues/5#issuecomment-282520108) what I think we should add.

**Comment by skibinska** [comment]
@lucymonie  are we expect that people will watch the video during the workshop?

**Comment by lucymonie** [comment]
@Jbarget we have come up with the questions above to ask after each readme section. Are you okay with these questions? Any suggestions?

**Comment by lucymonie** [comment]
@skibinska, the video is listed in the [precourse resources file](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/precourse/resources.md) so I would expect that they would have watched it already.

**Comment by Jbarget** [comment]
Hey hey, I think the questions themselves are good but I'm sceptical about being able to fit this all in with the time allocated for it in master reference. 

The questions could result in a 30-45 minute discussion so I think some restructuring of the day might be appropriate if you want to add them in.

It's a lot for them to take in: APIs, request, response, asynchronous in the space of 5 hours (realistically 4 hours of concentration) between 10-1. The list of questions is similar to their learning outcomes which are the outcomes of the whole week rather than the morning of the first day. So I'd be weary of opening up a whole discussion on those questions Without giving it the appropriate time

**Comment by lucymonie** [comment]
Hmm. Just to clarify, the questions aren't an afterthought, they're key to this workshop. @skibinska and I felt that it was really important to have more than them reading the documents. We want them actively discussing and answering questions. 

I don't think there's too much point them doing the exercises if they haven't got a proper mental model of the concepts involved.

@skibinska raised the same concern about the number of questions. Could we compromise and make it one or two key questions per section?

**Comment by lucymonie** [comment]
And isn't it 3 hours @Jbarget?! Or do you have some sort of tardis? :smiley:

**Comment by Jbarget** [comment]
ha whoops 3 hours :) 
for the moment @jmurphyweb and I are going to ask one/two questions out of the ones listed above. Will let you know how it goes :)

**Comment by skibinska** [comment]
@lucymonie I think we should ask two first questions from each section.

I don't think we should ask questions related to the video. Even that this is a precourse resource I would not expect that everyone will remember what going on there.

**Comment by Jbarget** [comment]
With a little live coding in the browser console we asked questions around the points below, didnt ask them exactly but around those points:

Request/Response: 
- What is the request property responseText?
- What JSON method can we use to transform a responseText string into something we can use?

Http:
- Name three HTTP methods.

XMLHttpRequest:
- How many parameters does the open method expect? Could you explain what they are?
- Why do we check on the onreadystatechange property?

Asynchronous: we didnt actually have time for them to read this section and felt it was ok to set it as *extra reading* since it wasn't integral to introducing them to APIs.

We often found ourselves cutting them short of finishing reading a section as we wanted to make sure we went through the main points of each section as a group
